language: csharp
sudo: required
dist: trusty
solution: Vigil.sln
mono: none
dotnet: 1.0.0-rc4-004771
install:
    - nuget restore $TAVIS_SOLUTION
script:
    - xbuild /p:Configuration=Release $TRAVIS_SOLUTION
matrix:
  include:
    - dotnet: 1.0.0-rc4-004771