language: csharp
sudo: required
dist: trusty
solution: Vigil.sln

install:
    - nuget restore $TAVIS_SOLUTION
script:
    - xbuild /p:Configuration=Release $TRAVIS_SOLUTION
matrix:
  include:
    - dotnet: 1.0.0-rc4-004771
      mono: none
      env: FRAMEWORK=netcoreapp1.1 DOTNETCORE=1