language: csharp
solution: Vigil.sln
dotnet: 1.0.0-preview2-1-003177
install:
  - nuget restore Vigil.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Vigil.sln
  - mono ./testrunn/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./test/Vigil.Domain.Tests/bin/Release/Vigil.Domain.Tests.dll
  - mono ./testrunn/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./test/Vigil.Patrons.Tests/bin/Release/Vigil.Patrons.Tests.dll
  - mono ./testrunn/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./test/Vigil.WebApi.Tests/bin/Release/Vigil.WebApi.Tests.dll