// <auto-generated />
namespace Vigil.Data.Modeling.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PatronPersonInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PatronPersonInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201510162049096_PatronPersonInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
