// <auto-generated />
namespace Vigil.Data.Modeling.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_CreatedBy_ModifedBy_DeletedBy_To_String : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_CreatedBy_ModifedBy_DeletedBy_To_String));
        
        string IMigrationMetadata.Id
        {
            get { return "201512181803264_Change_CreatedBy_ModifedBy_DeletedBy_To_String"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
